# Generated by Django 3.2.3 on 2021-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='backgroundcheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'backgroundcheck',
                'verbose_name_plural': 'backgroundcheck',
            },
        ),
        migrations.CreateModel(
            name='bountyhunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'bountyhunter',
                'verbose_name_plural': 'bountyhunter',
            },
        ),
        migrations.CreateModel(
            name='debtrecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'debtrecovery',
                'verbose_name_plural': 'debtrecovery',
            },
        ),
        migrations.CreateModel(
            name='liedetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'liedetector',
                'verbose_name_plural': 'liedetector',
            },
        ),
        migrations.CreateModel(
            name='missingperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'missingperson',
                'verbose_name_plural': 'missingperson',
            },
        ),
        migrations.CreateModel(
            name='surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'surveillance',
                'verbose_name_plural': 'surveillance',
            },
        ),
        migrations.CreateModel(
            name='undercoverinvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(default='default.jpg', upload_to='img/%y')),
                ('img2', models.ImageField(default='default.jpg', upload_to='img/%y')),
            ],
            options={
                'verbose_name': 'undercoverinvestigation',
                'verbose_name_plural': 'undercoverinvestigation',
            },
        ),
        migrations.AlterModelOptions(
            name='armedsecurity',
            options={'verbose_name': 'Armedsecurity', 'verbose_name_plural': 'Armedsecurity'},
        ),
        migrations.AlterModelOptions(
            name='commercialsecurity',
            options={'verbose_name': 'Commercialsecurity', 'verbose_name_plural': 'Commercialsecurity'},
        ),
        migrations.AlterModelOptions(
            name='contractsecurity',
            options={'verbose_name': 'Contractsecurity', 'verbose_name_plural': 'Contractsecurity'},
        ),
        migrations.AlterModelOptions(
            name='crossingguards',
            options={'verbose_name': 'Crossingguards', 'verbose_name_plural': 'Crossingguards'},
        ),
        migrations.AlterModelOptions(
            name='homesecuritysystem',
            options={'verbose_name': 'Homesecuritysystem', 'verbose_name_plural': 'Homesecuritysystem'},
        ),
        migrations.AlterModelOptions(
            name='multifamilysolution',
            options={'verbose_name': 'Multifamilysolution', 'verbose_name_plural': 'Multifamilysolution'},
        ),
        migrations.AlterModelOptions(
            name='professionalsecurity',
            options={'verbose_name': 'Professionalsecurity', 'verbose_name_plural': 'Professionalsecurity'},
        ),
        migrations.AlterModelOptions(
            name='securityforrenters',
            options={'verbose_name': 'Securityforrenters', 'verbose_name_plural': 'Securityforrenters'},
        ),
        migrations.AlterModelOptions(
            name='securitymonitoring',
            options={'verbose_name': 'Securitymonitoring', 'verbose_name_plural': 'Securitymonitoring'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Teams', 'verbose_name_plural': 'Teams'},
        ),
    ]
