# Generated by Django 3.2.3 on 2021-08-06 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210806_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundcheck',
            options={'verbose_name': 'Backgroundcheck', 'verbose_name_plural': 'Backgroundcheck'},
        ),
        migrations.AlterModelOptions(
            name='bountyhunter',
            options={'verbose_name': 'Bountyhunter', 'verbose_name_plural': 'Bountyhunter'},
        ),
        migrations.AlterModelOptions(
            name='debtrecovery',
            options={'verbose_name': 'Debtrecovery', 'verbose_name_plural': 'Debtrecovery'},
        ),
        migrations.AlterModelOptions(
            name='liedetector',
            options={'verbose_name': 'Liedetector', 'verbose_name_plural': 'Liedetector'},
        ),
        migrations.AlterModelOptions(
            name='missingperson',
            options={'verbose_name': 'Missingperson', 'verbose_name_plural': 'Missingperson'},
        ),
        migrations.AlterModelOptions(
            name='surveillance',
            options={'verbose_name': 'Surveillance', 'verbose_name_plural': 'Surveillance'},
        ),
        migrations.AlterModelOptions(
            name='undercoverinvestigation',
            options={'verbose_name': 'Undercoverinvestigation', 'verbose_name_plural': 'Undercoverinvestigation'},
        ),
    ]
