# Generated by Django 3.2.7 on 2021-11-17 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_executiveprotection_intelligenttraining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Armedsecurity',
        ),
        migrations.DeleteModel(
            name='backgroundcheck',
        ),
        migrations.DeleteModel(
            name='bountyhunter',
        ),
        migrations.DeleteModel(
            name='Commercialsecurity',
        ),
        migrations.DeleteModel(
            name='Contractsecurity',
        ),
        migrations.DeleteModel(
            name='Crossingguards',
        ),
        migrations.DeleteModel(
            name='debtrecovery',
        ),
        migrations.DeleteModel(
            name='Executiveprotection',
        ),
        migrations.DeleteModel(
            name='Homesecuritysystem',
        ),
        migrations.DeleteModel(
            name='Intelligenttraining',
        ),
        migrations.DeleteModel(
            name='liedetector',
        ),
        migrations.DeleteModel(
            name='missingperson',
        ),
        migrations.DeleteModel(
            name='Multifamilysolution',
        ),
        migrations.DeleteModel(
            name='Professionalsecurity',
        ),
        migrations.DeleteModel(
            name='Securityforrenters',
        ),
        migrations.DeleteModel(
            name='Securitymonitoring',
        ),
        migrations.DeleteModel(
            name='surveillance',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
        migrations.DeleteModel(
            name='undercoverinvestigation',
        ),
    ]
